name: Norne

flownet:
  data_source:
    simulation:
      input_case: ../input_model/norne/NORNE_ATW2013
      vectors:
        WBHP:
          rel_error: 0.05
          min_error: 10
        WOPR:
          rel_error: 0.1
          min_error: 50
        WGPR:
          rel_error: 0.1
          min_error: 100000
    concave_hull: true
  phases:
    - oil
    - gas
    - vapoil
    - disgas
    - water
  pvt:
    rsvd: norne_static/rsvd.csv
  cell_length: 100
  additional_flow_nodes: 200
  additional_node_candidates: 1000
  hull_factor: 1.2
  random_seed: 123456
  perforation_handling_strategy: time_avg_open_location
  fast_pyscal: true
  training_set_end_date: 2005-01-31
  fault_tolerance: 0.1
  max_distance_fraction: 0.15

ert:
  static_include_files: ./norne_static
  realizations:
    num_realizations: 200
    required_success_percent: 70
    max_runtime: 600   # Maximum runtime of on single realization in seconds
  queue:
    system: LOCAL   # LOCAL or LSF
    name: mr   # ignored when system is LOCAL
    max_running: 10   # Maximum number of simultaneous runs
  ensemble_weights:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1

model_parameters:
  permeability:
    min: 0.1
    max: 5000
  porosity:
    min: 0.01
    max: 0.4
  bulkvolume_mult:
    mean: 1
    max: 2
  fault_mult:
    min: 1.0e-3
    max: 1
    loguniform: true
  relative_permeability:
    scheme: global
    swirr:
      min: 0.01
      max: 0.04
    swl:
      min: 0.05
      max: 0.09
    swcr:
      min: 0.30
      max: 0.35
    sorw:
      min: 0.2
      max: 0.3
    sorg:
      min: 0.4
      max: 0.5
    sgcr:
      min: 0.03
      max: 0.08
    krwend:
      min: 0.5
      max: 0.7
    krowend:
      min: 0.3
      max: 0.5
    krgend:
      min: 0.9
      max: 1.0
    krogend:
      min: 0.9
      max: 1.0
    nw:
      min: 0.5
      max: 2.5
    now:
      min: 0.5
      max: 1.0
    ng:
      min: 1.0
      max: 1.5
    nog:
      min: 1.5
      max: 2.0
  equil:
    scheme: regions_from_sim
    eqlnum_region:
      - datum_depth: 2575
        datum_pressure:
          min: 250
          max: 275
        owc_depth:
          min: 2675
          max: 2725
        goc_depth:
          min: 2575
          max: 2600
      - id: 1
        datum_depth: 2582
        datum_pressure:
          min: 250
          max: 275
        owc_depth:
          min: 2675
          max: 2725
        goc_depth:
          min: 2575
          max: 2600
      - id: 2
        datum_depth: 2500
        datum_pressure:
          min: 250
          max: 275
        owc_depth:
          min: 2555
          max: 2615
        goc_depth:
          min: 2470
          max: 2530
      - id: 3
        datum_depth: 2582
        datum_pressure:
          min: 250
          max: 275
        owc_depth:
          min: 2600
          max: 2640
        goc_depth:
          min: 2560
          max: 2600
      - id: 4
        datum_depth: 2200
        datum_pressure:
          min: 200
          max: 250
        owc_depth:
          min: 2350
          max: 2450
        goc_depth:
          min: 2150
          max: 2250
      - id: 5
        datum_depth: 2585
        datum_pressure:
          min: 250
          max: 275
        owc_depth:
          min: 2675
          max: 2725
        goc_depth:
          min: 2575
          max: 2600
  rock_compressibility:
    reference_pressure: 277
    min: 4.8e-5
    max: 5.2e-5
  aquifer:
    scheme: individual
    fraction: 0.25
    delta_depth: 1000
    size_in_bulkvolumes:
      min: 1.0e-6
      max: 2
      loguniform: true
