name: Norne

flownet:
  data_source:
    simulation:
      well_logs: false
      input_case: ../input_model/norne/NORNE_ATW2013
      vectors:
        WTHP:
          rel_error: 0.05
          min_error: 5
        WBHP:
          rel_error: 0.05
          min_error: 10
        WOPR:
          rel_error: 0.1
          min_error: 50
        WGPR:
          rel_error: 0.1
          min_error: 100000
        WWPR:
          rel_error: 0.1
          min_error: 50
    concave_hull: true
  phases:
    - oil
    - gas
    - vapoil
    - disgas
    - water
  pvt:
    rsvd: norne_static/rsvd.csv
  cell_length: 100
  additional_flow_nodes: 100
  additional_node_candidates: 1000
  hull_factor: 1.2
  random_seed: 123456
  perforation_handling_strategy: time_avg_open_location
  fast_pyscal: true
  training_set_end_date: 2005-01-31  # YYYY-MM-DD. If defined training set fraction is calculated from this date
  fault_tolerance: 0.0001
  max_distance_fraction: 0.10

ert:
  static_include_files: ./norne_static
  realizations:
    num_realizations: 250
    required_success_percent: 50
    max_runtime: 600   # Maximum runtime of on single realization in seconds
  queue:
    system: LOCAL   # LOCAL or LSF
    name: mr   # ignored when system is LOCAL
    max_running: 70   # Maximum number of simultaneous runs
  ensemble_weights:
    - 4
    - 3
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1

model_parameters:
  permeability:
    min: 10
    max: 1000
  porosity:
    min: 0.05
    max: 0.35
  bulkvolume_mult:
    min: 0.1
    max: 20
  fault_mult:
    min: 1.0e-5
    max: 1
    loguniform: true
  relative_permeability:
    scheme: individual
    swirr:
      min: 0.01
      max: 0.04
    swl:
      min: 0.05
      max: 0.09
    swcr:
      min: 0.1
      max: 0.3
    sorw:
      min: 0.2
      max: 0.3
    sorg:
      min: 0.1
      max: 0.2
    sgcr:
      min: 0.03
      max: 0.08
    krwend:
      min: 0.4
      max: 0.6
    krowend:
      min: 0.9
      max: 1.0
    krgend:
      min: 0.9
      max: 1.0
    krogend:
      min: 0.9
      max: 1.0
    nw:
      min: 1.5
      max: 3.0
    now:
      min: 1.5
      max: 3.0
    ng:
      min: 1.5
      max: 3.0
    nog:
      min: 1.5
      max: 3.0
  equil:
    scheme: individual
    datum_pressure:
      min: 240
      max: 270
    goc_depth:
      min: 2450
      max: 2590
    owc_depth:
      min: 2601
      max: 2700
#  rock_compressibility:
#    reference_pressure: 277
#    min: 4.8e-5
#    max: 5.2e-5
#  aquifer:
#    scheme: individual
#    fraction: 0.25
#    delta_depth: 1000
#    size_in_bulkvolumes:
#      min: 1.0e-6
#      max: 2
#      loguniform: true
